application: start-blog-react
version: 1
runtime: php55
api_version: 1
threadsafe: false

builtins:
- appstats: on
- deferred: on
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /favicon\.ico
  static_files: vendor/favicon.ico
  upload: vendor/favicon.ico
  mime_type: image/vnd.microsoft.icon

- url: /robots\.txt
  static_files: vendor/robots.txt
  upload: vendor/robots.txt

- url: /static
  static_dir: static
  application_readable: true

- url: /vendor
  static_dir: vendor
  application_readable: true

  # Serve php scripts.
- url: /(.+\.(php|html))$
  script: \1

- url: /
  script: index.html